baseURL = 'https://example.com/'
languageCode = 'en-us'
title = 'Nebula System'
theme = ['PaperMod', 'hugo-embed-pdf-shortcode']
copyright = "© Nebula"
enableInlineShortcodes = true

[params]
hideSummary = false

[params.homeInfoParams]
Title = "Hi there👋"
Content = "We're Nebula, a system of critters who are trying their best."

[[params.socialIcons]]
name = "Github"
url = "https://github.com/lyricalpaws"

[[params.socialIcons]]
name = "Telegram"
url = "https://t.me/lyricalpaws"

[[params.socialIcons]]
name = "Twitter"
url = "https://x.com/lyricalpaws"

[[params.socialIcons]]
name = "Email"
url = "mailto:nebula@neb.gay"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2

[[menu.main]]
name = "Comms"
url = "/commissions"
weight = 3

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 4

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 5

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true