baseURL = 'https://example.com/'
languageCode = 'en-us'
title = 'Nebula System'
theme = ['archie', 'hugo-embed-pdf-shortcode']
copyright = "© Nebula"
enableInlineShortcodes = true

[params]
	mode="dark"
	useCDN=false
	subtitle = "A bunch of critters sharing a home in 1 body."
    email = "nebula@neb.gay"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/lyricalpaws"

[[params.social]]
name = "Email"
url = "mailto:nebula@neb.gay"
icon = "mail"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true